// All images served locally from /public/images/ — no external dependency
// Data for Avinterra Expeditions
const I = (name: string) => `/images/${name}`;

// WhatsApp contact number (international format, no +)
export const WA_NUMBER = "254141920923";
export const WA_DISPLAY = "+254 141 920923";

// Booking / calling number
export const BOOKING_PHONE = "+254 143 218 102";
export const BOOKING_PHONE_TEL = "+254143218102";

export const PHOTOS = {
  balloons:     I("balloons.jpg"),
  safari:       I("safari.jpg"),
  fuji:         I("fuji.jpg"),
  diani:        I("diani.jpg"),
  // Hotel / lodge imagery — used in About page
  aboutA:       I("hotel-dining.jpg"),
  aboutB:       I("hotel-pool.jpg"),
  hotel1:       I("hotel-pool.jpg"),
  hotel2:       I("hotel-dining.jpg"),
  hotel3:       I("hotel-coastal.jpg"),
  lodge1:       I("lodge.jpg"),
  lodge2:       I("luxury-camp.jpg"),
  mara:         I("mara.jpg"),
  amboseli:     I("amboseli.jpg"),
  beach:        I("beach.jpg"),
  mtkenya:      I("mtkenya.jpg"),
  tsavo:        I("safari.jpg"),
  cultural:     I("cultural.jpg"),
  dubai:        I("dubai.jpg"),
  greece:       I("greece.jpg"),
  japan:        I("fuji.jpg"),
  egypt:        I("egypt.jpg"),
  zanzibar:     I("zanzibar.jpg"),
  sa:           I("cultural.jpg"),
  lion:         I("lion-mara.jpg"),
  elephant:     I("amboseli.jpg"),
  leopard:      I("leopard.jpg"),
  buffalo:      I("buffalo.jpg"),
  rhino:        I("rhino.jpg"),
  pkgGreece:    I("pkg-greece.jpg"),
  pkgMexico:    I("pkg-mexico.jpg"),
  pkgJapan:     I("pkg-japan.jpg"),
  pkgMtKenyaHike: I("pkg-mtkenya-hike.jpg"),
  pkgLongonot:  I("pkg-longonot.jpg"),
  pkgMasaiMara: I("pkg-masai-mara.jpg"),
  pkgKiambicho: I("pkg-kiambicho.jpg"),
  pkgPrideInn:  I("pkg-prideinn.jpg"),
  pkgSaltys:    I("pkg-saltys.jpg"),
  pkgTsavo:     I("pkg-tsavo.jpg"),
  pkgPangoni:   I("pkg-pangoni.jpg"),
  pkgKaruru:    I("pkg-karuru.jpg"),
  pkgArkLodge:  I("pkg-ark-lodge.jpg"),
  pkgMasaiMaraNP: I("pkg-masai-mara-np.jpg"),
  pkgTsavoNP:   I("pkg-tsavo-np.jpg"),
  pkgJambo:     I("pkg-jambo.jpg"),
  pkgNakuru:    I("pkg-nakuru.jpg"),
  pkgNairobiNP: I("pkg-nairobi-np.jpg"),
  pkgSerengeti: I("pkg-serengeti.jpg"),
  pkgSouthernPalms: I("pkg-southern-palms.jpg"),
  pkgSunSand:   I("pkg-sun-sand.jpg"),
  pkgAmboseli:  I("pkg-amboseli.jpg"),
  gal1:         I("gal1.jpg"),
  gal2:         I("gal2.jpg"),
  gal3:         I("gal3.jpg"),
  gal4:         I("gal4.jpg"),
  gal5:         I("gal5.jpg"),
  gal6:         I("gal6.jpg"),
  avA:          I("av-a.jpg"),
  avB:          I("av-b.jpg"),
  avC:          I("av-c.jpg"),
  bookingArt:   I("gal6.jpg"),
  // International Posters
  posterAcropolis:   I("ACROPOLIS.jpg"),
  posterBangkok:     I("BANGKOK.jpg"),
  posterDubai:       I("DUBAI.jpg"),
  posterEgypt:       I("EGYPT.jpg"),
  posterEurope:      I("EUR.jpg"),
  posterFrance:      I("FRANCE.jpg"),
  posterGermany:     I("GERMANY.jpg"),
  posterGermanyAlt:  I("germany-poster-alt.jpg"),
  posterGreece:      I("GREECE.jpg"),
  posterIstanbul:    I("ISTANBUL.jpg"),
  posterIstanbulAlt: I("istanbul-poster-alt.jpg"),
  posterLondon:      I("LONDON.jpg"),
  posterMadagascar:    I("madagascar-poster.jpg"),
  posterMadagascarAlt: I("madagascar-poster-alt.jpg"),
  posterMaldives:      I("maldives-poster.jpg"),
  posterMexico:        I("mexico-poster.jpg"),
  posterNorthKorea:    I("north-korea-poster.jpg"),
  posterNorway:        I("norway-poster.jpg"),
  posterOslo:          I("OSLO.jpg"),
  posterRio:           I("rio-poster.jpg"),
  posterSingapore:     I("singapore-poster.jpg"),
  posterSouthAfrica:   I("south-africa-poster.jpg"),
  posterSouthKorea:    I("south-korea-poster.jpg"),
  posterSpain:         I("SPAIN.jpg"),
  posterThailand:      I("THAILAND.jpg"),
  cityPoster2:         I("city-poster-2.jpg"),
  cityPoster4:         I("city-poster-4.jpg"),
  cityPoster5:         I("city-poster-5.jpg"),
};

/** @deprecated kept for any remaining direct callers — prefer PHOTOS keys */
export const img = (): string => "";

export interface Destination {
  name: string;
  meta: string;
  price: string;
  img: string;
}

export const LOCAL: Destination[] = [
  { name: "Maasai Mara",         meta: "3 days · 2 nights · safari",  price: "KSH 19,500", img: PHOTOS.pkgMasaiMara },
  { name: "Masai Mara NP",       meta: "3 days · 2 nights · safari",  price: "KSH 37,500", img: PHOTOS.pkgMasaiMaraNP },
  { name: "Tsavo Safari",        meta: "3 days · 2 nights · safari",  price: "KSH 18,700", img: PHOTOS.pkgTsavo },
  { name: "Tsavo National Park", meta: "3 days · 2 nights · safari",  price: "KSH 18,700", img: PHOTOS.pkgTsavoNP },
  { name: "Mt Kenya Hike",     meta: "1 day · hiking & forest",      price: "KSH 3,500",  img: PHOTOS.pkgMtKenyaHike },
  { name: "Mt. Longonot",      meta: "1 day · hiking",               price: "KSH 4,500",  img: PHOTOS.pkgLongonot },
  { name: "Kiambicho Hills",   meta: "1 day · gorges & bridge",      price: "KSH 5,200",  img: PHOTOS.pkgKiambicho },
  { name: "Karuru Falls",      meta: "1 day · waterfall adventure",  price: "KSH 3,900",  img: PHOTOS.pkgKaruru },
  { name: "Salty's on the Creek", meta: "3 days · Kilifi water sports", price: "KSH 52,950", img: PHOTOS.pkgSaltys },
  { name: "PrideInn Paradise",   meta: "3 days · Mombasa beach & spa", price: "KSH 56,990", img: PHOTOS.pkgPrideInn },
  { name: "Pangoni Beach Resort",meta: "3 days · Mombasa resort & spa",price: "KSH 51,700", img: PHOTOS.pkgPangoni },
  { name: "The Ark Lodge",       meta: "3 days · Mt Kenya wildlife",   price: "KSH 32,670", img: PHOTOS.pkgArkLodge },
  { name: "Jambo Travellers Hotel", meta: "3 days · 2 nights · Mombasa", price: "KSH 23,700", img: PHOTOS.pkgJambo },
  { name: "Lake Nakuru NP",      meta: "1 day · flamingoes & game drive", price: "KSH 4,500", img: PHOTOS.pkgNakuru },
  { name: "Nairobi National Park", meta: "1 day · city wildlife",       price: "KSH 3,200",  img: PHOTOS.pkgNairobiNP },
  { name: "Serengeti",           meta: "3 days · 2 nights · Tanzania",  price: "KSH 45,500", img: PHOTOS.pkgSerengeti },
  { name: "Southern Palms Beach",meta: "coast · all inclusive",         price: "KSH 48,900", img: PHOTOS.pkgSouthernPalms },
  { name: "Sun & Sand Resort",   meta: "3 days · 2 nights · Diani",    price: "KSH 42,650", img: PHOTOS.pkgSunSand },
  { name: "Amboseli",            meta: "3 days · 2 nights · safari",   price: "KSH 19,600", img: PHOTOS.pkgAmboseli },
];

export const INTL: Destination[] = [
  { name: "Greece",            meta: "8 days · 7 nights · Athens / Mykonos / Santorini", price: "USD 5,369", img: PHOTOS.posterGreece },
  { name: "Mexico",            meta: "8 days · 7 nights · Mexico City",                  price: "USD 7,490", img: PHOTOS.posterMexico },
  { name: "Japan",             meta: "10 days · 11 nights · Tokyo · Kyoto · Mt Fuji",    price: "Contact us", img: PHOTOS.pkgJapan },
  { name: "Dubai",             meta: "5 days · city",     price: "USD 1,356", img: PHOTOS.posterDubai },
  { name: "Egypt",             meta: "8 days · history",  price: "USD 4,290", img: PHOTOS.posterEgypt },
  { name: "Zanzibar",          meta: "5 days · coast",    price: "USD   890", img: PHOTOS.zanzibar },
  { name: "Bangkok",           meta: "5 days · Thailand", price: "Contact us", img: PHOTOS.posterBangkok },
  { name: "Istanbul",          meta: "6 days · Turkey",   price: "Contact us", img: PHOTOS.posterIstanbul },
  { name: "London",            meta: "7 days · UK",       price: "Contact us", img: PHOTOS.posterLondon },
  { name: "Maldives",          meta: "5 days · island",   price: "Contact us", img: PHOTOS.posterMaldives },
  { name: "Rio de Janeiro",    meta: "8 days · Brazil",   price: "Contact us", img: PHOTOS.posterRio },
  { name: "Singapore",         meta: "5 days · city",     price: "Contact us", img: PHOTOS.posterSingapore },
  { name: "South Africa",      meta: "7 days · safari",   price: "Contact us", img: PHOTOS.posterSouthAfrica },
  { name: "Paris, France",     meta: "6 days · city",     price: "Contact us", img: PHOTOS.posterFrance },
  { name: "Germany",           meta: "7 days · city",     price: "Contact us", img: PHOTOS.posterGermany },
  { name: "Spain",             meta: "8 days · culture",  price: "Contact us", img: PHOTOS.posterSpain },
  { name: "Norway",            meta: "7 days · fjords",   price: "Contact us", img: PHOTOS.posterNorway },
  { name: "South Korea",       meta: "6 days · tech",     price: "Contact us", img: PHOTOS.posterSouthKorea },
  { name: "Madagascar",        meta: "7 days · nature",   price: "Contact us", img: PHOTOS.posterMadagascar },
  { name: "North Korea",       meta: "5 days · culture",  price: "Contact us", img: PHOTOS.posterNorthKorea },
];

export interface Package {
  badge: string;
  intl: boolean;
  title: string;
  duration: string;
  price: string;
  img: string;
  inclusions?: string[];
  exclusions?: string[];
}

const INTL_PACKAGES: Package[] = [
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Greece",
    duration: "8 DAYS · 7 NIGHTS · ATHENS / MYKONOS / SANTORINI",
    price: "USD 5,369",
    img: PHOTOS.posterGreece,
    inclusions: [
      "All taxes & service charges",
      "Return economy flights from Nairobi",
      "3 nights Athens + 2 nights Mykonos + 2 nights Santorini (breakfast)",
      "All transfers by private vehicle & shuttle bus",
      "Ferry Piraeus – Mykonos (economy)",
      "Half-day Athens city tour with Acropolis Museum",
      "Hydrofoil Mykonos – Santorini – Piraeus (economy)",
      "Entrance fees per itinerary",
    ],
    exclusions: [
      "Visa fees",
      "Travel insurance",
      "Personal expenses & tips",
      "Accommodation taxes (paid locally)",
      "Porterage",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Mexico",
    duration: "8 DAYS · 7 NIGHTS · MEXICO CITY",
    price: "USD 7,490",
    img: PHOTOS.posterMexico,
    inclusions: [
      "Round-trip flights Nairobi (NBO) → Mexico City (MEX)",
      "7 nights luxury hotel (Marquis Reforma / Sheraton Maria Isabel)",
      "Unlimited gourmet meals – 5 restaurants + 24hr room service",
      "Premium alcoholic & non-alcoholic drinks (top-shelf brands)",
      "Daily breakfast, lunch, dinner + snacks",
      "Airport VIP fast-track transfers",
      "English/Swahili guide & driver (3 full days)",
      "Early access to Teotihuacan Pyramids",
      "After-hours private tour – Frida Kahlo Museum (Blue House)",
      "Chef's table at Pujol (World's Top 10 Restaurant – tasting menu)",
      "Temazcal ritual (50-min pre-Hispanic spa treatment)",
      "Hand-painted Mexican pottery gift in your suite",
    ],
    exclusions: [
      "Anything not in the inclusions, hotels & itinerary column",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Japan",
    duration: "10 DAYS · 11 NIGHTS · TOKYO · KYOTO · MT FUJI",
    price: "Contact us",
    img: PHOTOS.pkgJapan,
    inclusions: [
      "Meals: 10 breakfasts at the hotel",
      "10 nights accommodation",
      "Tokyo, Hiroshima, Kyoto, Osaka & Nara city tours",
      "Mt Fuji full-day tour",
      "Shinkansen bullet train Tokyo–Hiroshima–Shin-Osaka (ordinary reserved)",
      "Private transfers per itinerary (driver only)",
    ],
    exclusions: [
      "International flights",
      "Visa fee",
      "Travel insurance",
      "Night-surcharge airport/station transfers (21:00–06:00)",
      "Entrance fees",
      "Personal expenses",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Dubai",
    duration: "5 DAYS · 4 NIGHTS",
    price: "USD 1,356",
    img: PHOTOS.posterDubai,
    inclusions: [
      "Return flight tickets",
      "Dubai Visa + Insurance",
      "4 nights stay in a 4-star hotel",
      "Daily breakfast",
      "Desert Safari with BBQ Dinner",
      "Dhow Cruise with Dinner",
      "Half-day Dubai City Tour",
      "Airport transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Egypt",
    duration: "8 DAYS · 7 NIGHTS · CAIRO · NILE CRUISE",
    price: "USD 4,290",
    img: PHOTOS.posterEgypt,
    inclusions: [
      "Return flight tickets",
      "Egypt Visa",
      "3 nights Cairo (breakfast)",
      "3 nights Nile Cruise (full board)",
      "All transfers",
      "Private guided tours to Pyramids & Sphinx",
      "Valley of the Kings tour",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Bangkok & Pattaya",
    duration: "6 DAYS · 5 NIGHTS · THAILAND",
    price: "Contact us",
    img: PHOTOS.posterBangkok,
    inclusions: [
      "Return flights",
      "Thailand Visa",
      "3 nights Bangkok + 2 nights Pattaya",
      "Daily breakfast",
      "Coral Island tour with lunch",
      "Safari World & Marine Park",
      "All transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Istanbul & Cappadocia",
    duration: "7 DAYS · 6 NIGHTS · TURKEY",
    price: "Contact us",
    img: PHOTOS.posterIstanbul,
    inclusions: [
      "Return flights",
      "Turkey Visa",
      "Accommodation with breakfast",
      "Bosphorus Cruise",
      "Hot Air Balloon flight (optional)",
      "Cappadocia North & South tours",
      "Airport transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Paris & Swiss Alps",
    duration: "8 DAYS · 7 NIGHTS · EUROPE",
    price: "Contact us",
    img: PHOTOS.posterFrance,
    inclusions: [
      "Schengen Visa guidance",
      "Accommodation with breakfast",
      "Eiffel Tower summit access",
      "Seine River cruise",
      "Mount Titlis day trip",
      "Inter-city train transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Singapore & Bali",
    duration: "7 DAYS · 6 NIGHTS · SOUTHEAST ASIA",
    price: "Contact us",
    img: PHOTOS.posterSingapore,
    inclusions: [
      "Return flights",
      "Visas",
      "3 nights Singapore + 3 nights Bali",
      "Gardens by the Bay",
      "Sentosa Island",
      "Ubud & Kintamani tour",
      "Private transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "London City Break",
    duration: "6 DAYS · 5 NIGHTS · UNITED KINGDOM",
    price: "Contact us",
    img: PHOTOS.posterLondon,
    inclusions: [
      "UK Visa guidance",
      "Accommodation in Central London",
      "Daily breakfast",
      "London Eye & River Thames cruise",
      "Stonehenge & Windsor Castle tour",
      "Airport transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "South Africa Explorer",
    duration: "7 DAYS · 6 NIGHTS · CAPE TOWN · SUN CITY",
    price: "Contact us",
    img: PHOTOS.posterSouthAfrica,
    inclusions: [
      "Return flights",
      "South Africa Visa",
      "3 nights Cape Town + 3 nights Sun City",
      "Table Mountain cable car",
      "Cape Peninsula tour",
      "Game drives in Pilanesberg",
      "All transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Maldives Luxury Escape",
    duration: "5 DAYS · 4 NIGHTS · OVERWATER VILLA",
    price: "Contact us",
    img: PHOTOS.posterMaldives,
    inclusions: [
      "Return flights",
      "4 nights in a 5-star resort",
      "All-inclusive meal plan",
      "Speedboat/Seaplane transfers",
      "Snorkeling & water sports",
      "Sunset cruise",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Rio de Janeiro",
    duration: "8 DAYS · 7 NIGHTS · BRAZIL",
    price: "Contact us",
    img: PHOTOS.posterRio,
    inclusions: [
      "Return flights",
      "Brazil Visa guidance",
      "Luxury accommodation on Copacabana",
      "Christ the Redeemer tour",
      "Sugarloaf Mountain",
      "Samba show experience",
      "Private transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Norway & the Fjords",
    duration: "8 DAYS · 7 NIGHTS · OSLO · BERGEN",
    price: "Contact us",
    img: PHOTOS.posterNorway,
    inclusions: [
      "Return flights",
      "Schengen Visa guidance",
      "Fjord cruise",
      "Flam Railway journey",
      "Oslo city tour",
      "Scenic train Bergen–Oslo",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "South Korea Discovery",
    duration: "7 DAYS · 6 NIGHTS · SEOUL · BUSAN",
    price: "Contact us",
    img: PHOTOS.posterSouthKorea,
    inclusions: [
      "Return flights",
      "South Korea Visa",
      "Accommodation with breakfast",
      "Gyeongbokgung Palace",
      "DMZ Tour",
      "KTX Bullet train to Busan",
      "Airport transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "Madagascar Wildlife",
    duration: "7 DAYS · 6 NIGHTS · NATURE",
    price: "Contact us",
    img: PHOTOS.posterMadagascar,
    inclusions: [
      "Return flights",
      "Visa guidance",
      "Accommodation with breakfast",
      "National park entry fees",
      "Wildlife guided tours",
      "All transfers",
    ],
  },
  {
    badge: "INTERNATIONAL",
    intl: true,
    title: "North Korea Discovery",
    duration: "5 DAYS · 4 NIGHTS · CULTURE",
    price: "Contact us",
    img: PHOTOS.posterNorthKorea,
    inclusions: [
      "Return flights",
      "Visa support",
      "Full board accommodation",
      "Guided city tours",
      "Museum entrance fees",
      "All transfers",
    ],
  },
];

const LOCAL_PACKAGES: Package[] = [
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Masai Mara Safari",
    duration: "3 DAYS · 2 NIGHTS · MASAI MARA",
    price: "KSH 19,500 / person",
    img: PHOTOS.pkgMasaiMara,
    inclusions: [
      "Transport to & from Nairobi",
      "Entrance fee – Masai Mara National Park",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: [
      "Personal items",
      "Drinks",
      "Tips",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Masai Mara National Park",
    duration: "3 DAYS · 2 NIGHTS · MASAI MARA",
    price: "KSH 37,500 / person",
    img: PHOTOS.pkgMasaiMaraNP,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Masai Mara National Park",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: [
      "Personal items",
      "Drinks",
      "Tips",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Tsavo Safari",
    duration: "3 DAYS · 2 NIGHTS · TSAVO",
    price: "KSH 18,700 / person",
    img: PHOTOS.pkgTsavo,
    inclusions: [
      "Transport to & from",
      "Entrance fee",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: [
      "Personal items",
      "Drinks",
      "Tips",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Tsavo National Park",
    duration: "3 DAYS · 2 NIGHTS · TSAVO",
    price: "KSH 18,700 / person",
    img: PHOTOS.pkgTsavoNP,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Tsavo National Park",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: [
      "Personal items",
      "Drinks",
      "Tips",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Salty's on the Creek",
    duration: "3 DAYS · KILIFI · WATER SPORTS",
    price: "KSH 52,950 / person",
    img: PHOTOS.pkgSaltys,
    inclusions: [
      "Accommodation cottages/villas",
      "SGR economy class tickets to & fro",
      "Hotel transfers",
      "Village walk / Wasini tour",
      "Meals (breakfast, lunch & dinner)",
      "Dolphin tour",
      "Kisite Mpunguti N Park entry fees",
      "Dhow ride",
      "All entry fees",
      "Visit Shimoni Caves",
      "Unlimited photography",
      "Zumba dance",
    ],
    exclusions: [
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "PrideInn Paradise Beach & Spa",
    duration: "3 DAYS · 2 NIGHTS · SHANZU, MOMBASA",
    price: "KSH 56,990 / person",
    img: PHOTOS.pkgPrideInn,
    inclusions: [
      "3 days 2 nights accommodation",
      "Full board meal plan",
      "Welcome drink & fruit basket on arrival",
      "Free upgrade to VIP suite",
      "Complimentary bottle of wine",
      "Return economy class SGR tickets",
      "Return transfers SGR terminus Miritini to hotel",
      "Non-motorized water sports activities",
      "Free WiFi",
      "Daily entertainment",
    ],
    exclusions: [
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Pangoni Beach Resort & Spa",
    duration: "3 DAYS · 2 NIGHTS · SHANZU, MOMBASA",
    price: "KSH 51,700 / person",
    img: PHOTOS.pkgPangoni,
    inclusions: [
      "3 days 2 nights accommodation",
      "Full board meal plan",
      "Welcome drink & fruit basket on arrival",
      "Free upgrade to VIP suite",
      "Complimentary bottle of wine",
      "Return economy class SGR tickets",
      "Return transfers SGR terminus Miritini to hotel",
      "Non-motorized water sports activities",
      "Free WiFi",
      "Daily entertainment",
    ],
    exclusions: [
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "The Ark Lodge",
    duration: "3 DAYS · 2 NIGHTS · MT KENYA",
    price: "KSH 32,670 / person",
    img: PHOTOS.pkgArkLodge,
    inclusions: [
      "Full board accommodation",
      "Nature walk",
      "Bush dinner",
      "Horse riding",
      "Sundowner & sparkling wine",
      "Breakfast at open deck of The Ark",
      "Half-day game drive in 4×4",
    ],
    exclusions: [
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Kiambicho Hills & Murang'a Gorges",
    duration: "1 DAY · MURANG'A GORGES · SCARY BRIDGE",
    price: "KSH 5,200 / person",
    img: PHOTOS.pkgKiambicho,
    inclusions: [
      "Transport to & fro in luxury tablet fleet",
      "Entry fee",
      "Unlimited photography",
      "Kiambicho Hills traverse",
      "Murang'a Gorges",
      "Scary bridge hike",
      "Kiamuti Hills traverse",
      "Refill mineral water",
      "Lunch",
    ],
    exclusions: [
      "Anything not mentioned",
      "Tips & gratitude",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Mt. Longonot Hiking",
    duration: "1 DAY · MT LONGONOT",
    price: "KSH 4,500 / person",
    img: PHOTOS.pkgLongonot,
    inclusions: [
      "Entrance fee",
      "Transport to & fro in luxury tablet fleet",
      "Unlimited photography",
      "Refill mineral water",
      "Lunch",
    ],
    exclusions: [
      "Snacks & drinks",
      "Tips",
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Mt Kenya Hike & Castle Forest",
    duration: "1 DAY · MT KENYA · CASTLE FOREST",
    price: "KSH 3,500 / person",
    img: PHOTOS.pkgMtKenyaHike,
    inclusions: [
      "Transport to & fro in luxury tablet fleet",
      "Professional tour guides",
      "Mineral water & snacks",
      "KFS entry fees",
      "Guided hike to the falls",
      "Swimming at the falls",
      "Unlimited professional photography",
      "Team building",
      "Lunch",
    ],
    exclusions: [
      "Drinks",
      "Anything not mentioned above",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Karuru Falls Adventure",
    duration: "1 DAY · KARURU FALLS",
    price: "KSH 3,900 / person",
    img: PHOTOS.pkgKaruru,
    inclusions: [
      "Entrance fee",
      "Transport to & fro in luxury tablet fleet",
      "Unlimited photography",
      "Guide fee",
      "Refill mineral water",
      "Lunch",
    ],
    exclusions: [
      "Snacks & drinks",
      "Tips",
      "Anything else not mentioned",
    ],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Amboseli",
    duration: "3 DAYS · 2 NIGHTS · AMBOSELI",
    price: "KSH 19,600 / person",
    img: PHOTOS.pkgAmboseli,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Amboseli National Park",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Nairobi National Park",
    duration: "1 DAY · NAIROBI",
    price: "KSH 3,200 / person",
    img: PHOTOS.pkgNairobiNP,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Nairobi National Park & Animal Orphanage",
      "Game drive (Land Cruiser)",
      "Lunch (biriani/pilau, fruits, drinks)",
      "Professional tour guide",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Lake Nakuru National Park",
    duration: "1 DAY · NAKURU, KENYA",
    price: "KSH 4,500 / person",
    img: PHOTOS.pkgNakuru,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Lake Nakuru National Park & Menengai Crater",
      "Game drive (Land Cruiser)",
      "Lunch (biriani/pilau, fruits, drinks)",
      "Professional tour guide",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Serengeti",
    duration: "3 DAYS · 2 NIGHTS · SERENGETI, TANZANIA",
    price: "KSH 45,500 / person",
    img: PHOTOS.pkgSerengeti,
    inclusions: [
      "Transport to & from",
      "Entrance fee – Serengeti National Park",
      "Driver guide",
      "Meals on full board",
      "Professional tour guide",
      "Unlimited game drive (Land Cruiser)",
      "Team building activities",
      "Water bottles & games & fun",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Jambo Travellers Hotel",
    duration: "3 DAYS · 2 NIGHTS · MOMBASA",
    price: "KSH 23,700 / person",
    img: PHOTOS.pkgJambo,
    inclusions: [
      "3 days 2 nights accommodation",
      "Full board meal plan",
      "Welcome drink & fruit basket on arrival",
      "Free upgrade to VIP suite",
      "Complimentary bottle of wine",
      "Return economy class SGR tickets",
      "Return transfers SGR terminus Miritini to hotel",
      "Non-motorized water sports activities",
      "Free WiFi",
      "Daily entertainment",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Southern Palms Beach Resort",
    duration: "COAST · ALL INCLUSIVE · MOMBASA",
    price: "KSH 48,900 / person",
    img: PHOTOS.pkgSouthernPalms,
    inclusions: [
      "Return flights tickets",
      "Private transfers return",
      "Meals on all inclusive",
      "Assorted alcoholic & non-alcoholic drinks",
      "Accommodation as per room type chosen",
      "Use of hotel facilities",
      "Entertainment day and night",
    ],
    exclusions: ["Anything else not mentioned"],
  },
  {
    badge: "LOCAL · KE",
    intl: false,
    title: "Sun & Sand Beach Resort",
    duration: "3 DAYS · 2 NIGHTS · DIANI, UKUNDA",
    price: "KSH 42,650 / person",
    img: PHOTOS.pkgSunSand,
    inclusions: [
      "2 nights accommodation",
      "1 complimentary free night accommodation",
      "Return flight / train tickets",
      "Full board meal plan",
      "Return transfers in Mombasa",
      "Use of hotel facilities",
    ],
    exclusions: ["Anything else not mentioned"],
  },
];

export const PACKAGES: Package[] = [...INTL_PACKAGES, ...LOCAL_PACKAGES];

export interface WhyItem {
  n: string;
  t: string;
  d: string;
  icon: string;
}

export const WHY: WhyItem[] = [
  { n: "01", t: "Affordable prices",  d: "Group discounts and lipa-polepole deposits as low as KSH 10,000.", icon: "M12 2v20M5 7l7-3 7 3M5 17l7 3 7-3" },
  { n: "02", t: "Experienced guides", d: "A decade of expedition leaders who know every viewpoint by name.",  icon: "M12 22s8-7 8-13a8 8 0 10-16 0c0 6 8 13 8 13zM12 9a3 3 0 100 6 3 3 0 000-6z" },
  { n: "03", t: "Secure travel",      d: "Verified accommodation, vetted transport, fully insured itineraries.", icon: "M12 2l8 4v6c0 5-3.5 9-8 10-4.5-1-8-5-8-10V6l8-4z" },
  { n: "04", t: "Custom packages",    d: "Pick the rhythm — slow honeymoon, fast family run, or solo deep dive.", icon: "M3 6h18M3 12h18M3 18h12" },
  { n: "05", t: "24/7 support",       d: "We're a WhatsApp away the entire time you're on the road.", icon: "M21 12c0 4.5-4 8-9 8-1.5 0-3-.3-4.3-1L3 20l1-4.7C3.3 14 3 12.5 3 12c0-4.5 4-8 9-8s9 3.5 9 8z" },
  { n: "06", t: "Trusted partners",   d: "Airlines, hotels and operators we've worked with for years, not weeks.", icon: "M9 12l2 2 4-4M12 2a10 10 0 100 20 10 10 0 000-20z" },
];

export interface Testimonial {
  q: string;
  n: string;
  role: string;
  av: string;
  s: number;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    q: "Avinterra planned our Mara trip top-to-bottom. The guide knew where the cats were, the lodge was spotless, and the price was exactly what they quoted. We're booking Greece next.",
    n: "Wanjiku M.", role: "MAASAI MARA · 2025", av: PHOTOS.avA, s: 5,
  },
  {
    q: "Our Japan honeymoon felt completely bespoke. Train tickets, ryokan, the lot — they sorted the visa and we just packed. Easily the smoothest international trip I've taken.",
    n: "James & Lina O.", role: "JAPAN · 2025", av: PHOTOS.avB, s: 5,
  },
  {
    q: "Booked the Salty's on the Creek weekend with twelve friends. Lipa-polepole made it painless and the dhow ride at sunset — I have no words. Just go.",
    n: "Brian K.", role: "KILIFI · 2024", av: PHOTOS.avC, s: 5,
  },
];

export interface GalleryItem {
  cls: string;
  src: string;
  cap: string;
}

export const GALLERY: GalleryItem[] = [
  { cls: "g-1", src: PHOTOS.mara,     cap: "MAASAI MARA" },
  { cls: "g-2", src: PHOTOS.beach,    cap: "DIANI BEACH" },
  { cls: "g-3", src: PHOTOS.greece,   cap: "MYKONOS" },
  { cls: "g-4", src: PHOTOS.lion,     cap: "AFRICAN LION" },
  { cls: "g-5", src: PHOTOS.leopard,  cap: "LEOPARD · TSAVO" },
  { cls: "g-6", src: PHOTOS.dubai,    cap: "DUBAI" },
];

export interface BigFiveAnimal {
  key: string;
  name: string;
  location: string;
  fact: string;
  img: string;
}

export const BIG_FIVE: BigFiveAnimal[] = [
  { key: "lion",     name: "Lion",     location: "MAASAI MARA",   fact: "Big Five · Kenya",    img: PHOTOS.lion },
  { key: "elephant", name: "Elephant", location: "AMBOSELI",      fact: "Big Five · Kenya",    img: PHOTOS.elephant },
  { key: "leopard",  name: "Leopard",  location: "TSAVO",         fact: "Big Five · Kenya",    img: PHOTOS.leopard },
  { key: "buffalo",  name: "Buffalo",  location: "LAKE NAKURU",   fact: "Big Five · Kenya",    img: PHOTOS.buffalo },
  { key: "rhino",    name: "Rhino",    location: "OL PEJETA",     fact: "Big Five · Kenya",    img: PHOTOS.rhino },
];
